#ifndef BOX2D_MOTOR_HPP
#define BOX2D_MOTOR_HPP

#include "physics/i_actuator.hpp"
#include "physics/i_motor.hpp"
#include "box2d/box2d.h"
#include "constants.hpp"
#include "micrasverse_core/types.hpp"
namespace micrasverse::physics {

class Box2DMotor : public IMotor {
public:
    Box2DMotor(b2BodyId bodyId, const types::Vec2& localPosition, bool leftWheel, 
               float angle = B2_PI / 2.0f, float R = MOTOR_RESISTANCE, 
               float ke = MOTOR_KE, float kt = MOTOR_KT, 
               float maxVoltage = MOTOR_MAX_VOLTAGE);
    virtual ~Box2DMotor() = default;

    // IActuator interface implementation
    ActuatorType getType() const override { return ActuatorType::MOTOR; }
    types::Vec2 getPosition() const override;
    
    void setCommand(float command) override;
    float getCommand() const override { return inputCommand; }
    
    bool isActive() const override { return std::abs(inputCommand) > 0.1f; }
    void update(float deltaTime) override { update(deltaTime, isFanOn); }
    void update(float deltaTime, bool isFanOn) override;
    
    // IMotor interface implementation
    float getCurrent() const override { return current; }
    float getAngularVelocity() const override { return angularVelocity; }
    float getAppliedForce() const override { return appliedForce; }
    float getTorque() const override { return torque; }
    float getBodyLinearVelocity() const override { return bodyLinearVelocity; }
    float getBodyAngularVelocity() const override { return bodyAngularVelocity; }
    bool isLeftWheel() const override { return leftWheel; }
    bool getFanState() const override { return isFanOn; }

private:
    float resistance;           // Motor resistance (R)
    float ke;                   // Back EMF constant
    float kt;                   // Torque constant
    float maxVoltage;           // Maximum input voltage
    float inputCommand;         // Motor command (-100 to +100)
    float current;              // Current through the motor
    float angularVelocity;      // Angular velocity of the rotor
    float frictionCoefficient;  // Coefficient of friction (mu)
    float bodyMass;             // Mass of the body
    float appliedForce;         // Force applied by the motor
    float torque;               // Torque generated by the motor
    float bodyLinearVelocity;   // Linear velocity of the body
    float bodyAngularVelocity;  // Angular velocity of the body
    bool leftWheel;             // Is this a left wheel?
    bool isFanOn;               // Is the fan on?

    // Box2D specific properties
    b2BodyId bodyId;            // Body to apply the force to
    b2Vec2 localPosition;       // Changed from types::Vec2 to b2Vec2
    b2Vec2 localDirection;      // Changed from types::Vec2 to b2Vec2
    float angle;                // Angle of the motor on the body
};

} // namespace micrasverse::physics

#endif // BOX2D_MOTOR_HPP 
